# Generated by Django 2.2.2 on 2019-06-28 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TD', 'To Do'), ('D', 'Done')], default='TD', max_length=100)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_To', to=settings.AUTH_USER_MODEL)),
                ('assigner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_By', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
