# Generated by Django 2.2.2 on 2019-07-02 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20190702_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 12, 35, 41, 652826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2293, 4, 15, 12, 35, 41, 652826, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 12, 35, 41, 652826, tzinfo=utc), null=True),
        ),
    ]
