# Generated by Django 2.2.2 on 2019-07-04 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_auto_20190702_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 12, 5, 27, 560773, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2293, 4, 17, 12, 5, 27, 560773, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 4, 12, 5, 27, 560773, tzinfo=utc), null=True),
        ),
    ]
