# Generated by Django 2.2.2 on 2019-07-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20190629_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring',
            field=models.CharField(choices=[('N', 'Never'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='N', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
