# Generated by Django 2.2.2 on 2019-07-04 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0010_auto_20190704_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=1000)),
                ('sender', models.CharField(default='taskmanageraravind@gmail.com', max_length=1000)),
                ('reciever', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 16, 53, 9, 936278, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2293, 4, 17, 16, 53, 9, 936278, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 4, 16, 53, 9, 936278, tzinfo=utc), null=True),
        ),
    ]
