# Generated by Django 2.2.2 on 2019-07-06 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0011_auto_20190704_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Late'), ('T', 'Today'), ('W', 'Week'), ('D', 'Default')], default='D', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 10, 35, 22, 317675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2293, 4, 19, 10, 35, 22, 317675, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 6, 10, 35, 22, 317675, tzinfo=utc), null=True),
        ),
    ]
