# Generated by Django 2.1 on 2019-10-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asend', '0002_auto_20191026_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='entries',
            field=models.ManyToManyField(blank=True, null=True, related_name='entries', to='asend.Entry'),
        ),
    ]
