# Generated by Django 2.1 on 2019-10-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asend', '0003_auto_20191026_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='metric',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
