# Generated by Django 2.1 on 2019-10-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asend', '0005_auto_20191026_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='category',
            name='metric',
        ),
    ]
