# Generated by Django 2.1 on 2019-10-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asend', '0006_auto_20191026_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='metric',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
