# Generated by Django 2.1 on 2019-10-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asend', '0007_category_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
